# disable ctrl+s to stop the terminal, as vim might need this hotkey
stty -ixon <$TTY >$TTY

ZSH_AUTOSUGGEST_STRATEGY=(completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_USE_ASYNC=1
ZSH_AUTOSUGGEST_MANUAL_REBIND=1
ZSH_AUTOSUGGEST_COMPLETION_IGNORE='( |man |pikaur -S )*'

CLICOLORS=1
alias ls='ls -F'
if [[ $(uname) == 'Linux' ]]; then
  alias ls='ls --color=auto -F'
fi

# find files with colored output, actually we should use fd
alias f='find . | grep --color'
alias nr='npm run'
alias dn='dotnet'
alias d-c='docker-compose'
alias gt='git tree'
alias pw='pwsh -c'
alias gt='git tree'
alias gst='git status'
alias gd='git diff'
alias http='xh'

# neovim is the future
if hash nvim 2>/dev/null; then
  alias vim=\\nvim realvim=\\vim
fi

setopt auto_cd

function curlperf {
  curl -o /dev/null -s -w "time_namelookup=%{time_namelookup}\ntime_connect=%{time_connect}\ntime_appconnect=%{time_appconnect}\ntime_total=%{time_total}\n" "$1"
}

HISTFILE=~/.zsh_history
# set session history size
HISTSIZE=10000
# set saved history size
SAVEHIST=10000

# zsh+tmux might introduce dup PATH, dedup it
typeset -aU path
# make ctrl+u same as bash. To delete entire line, use ctrl+c
bindkey \^U backward-kill-line

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -d ~/.fnm ] && eval "$(fnm env)"
# END OF PRE-CONFIGURED ZSHRC
